import { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import { Wallet, TrendingUp, AlertTriangle, PiggyBank, ArrowUpRight, ArrowDownRight, Plus, Download, FileText } from 'lucide-react';
import clsx from 'clsx';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Label } from 'recharts';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const Dashboard = () => {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [month, setMonth] = useState(new Date().getMonth() + 1);
    const [year, setYear] = useState(new Date().getFullYear());
    const dashboardRef = useRef(null);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const res = await axios.get(`/api/analytics?month=${month}&year=${year}`);
                setData(res.data);
            } catch (error) {
                console.error("Error fetching dashboard data:", error);
            } finally {
                setLoading(false);
            }
        };
        fetchData();
    }, [month, year]);

    const handleExportPDF = async () => {
        const element = dashboardRef.current;
        if (!element) return;

        const canvas = await html2canvas(element, { scale: 2, backgroundColor: '#ffffff' });
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

        pdf.setFillColor(255, 255, 255);
        pdf.rect(0, 0, pdfWidth, pdf.internal.pageSize.getHeight(), 'F');

        pdf.setFontSize(18);
        pdf.setTextColor(40);
        pdf.text("Student Expense Report", 15, 20);
        pdf.setFontSize(12);
        pdf.setTextColor(100);
        pdf.text(`Period: ${new Date(year, month - 1).toLocaleString('default', { month: 'long' })} ${year}`, 15, 30);

        pdf.addImage(imgData, 'PNG', 10, 40, pdfWidth - 20, pdfHeight - 20); // Scaled to fit

        pdf.setFontSize(10);
        pdf.setTextColor(150);
        pdf.text("Generated by ExpenseTracker", pdfWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });

        pdf.save(`Expense_Report_${month}_${year}.pdf`);
    };

    if (loading) return <div className="p-8 text-center text-slate-500 animate-pulse">Loading dashboard...</div>;

    const COLORS = ['#0ea5e9', '#6366f1', '#10b981', '#f59e0b', '#ef4444'];
    const pieData = data?.categoryData ? Object.entries(data.categoryData).map(([name, value]) => ({ name, value })) : [];

    const StatCard = ({ title, value, icon: Icon, color, subtext }) => (
        <div className="card group cursor-default relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <Icon size={48} className={color.replace("bg-", "text-")} />
            </div>
            <div className="flex items-center justify-between mb-4 relative z-10">
                <div className={clsx("p-3 rounded-xl bg-opacity-20", color)}>
                    <Icon size={24} className={color.replace("bg-", "text-")} />
                </div>
                {subtext && <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-700/50 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-600">{subtext}</span>}
            </div>
            <div className="relative z-10">
                <p className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide">{title}</p>
                <h3 className="text-3xl font-bold mt-1 text-slate-800 dark:text-white tracking-tight">
                    ₹{value?.toLocaleString() || 0}
                </h3>
            </div>
        </div>
    );

    return (
        <div className="space-y-8" ref={dashboardRef}>
            {/* Header Section */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h2 className="text-3xl font-bold text-slate-800 dark:text-white tracking-tight">Dashboard</h2>
                    <p className="text-slate-500 dark:text-slate-400 mt-1">Overview for {new Date(year, month - 1).toLocaleString('default', { month: 'long' })} {year}</p>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                    <div className="flex bg-white dark:bg-slate-800 rounded-lg p-1 shadow-sm border border-slate-200 dark:border-slate-700">
                        <select
                            value={month}
                            onChange={(e) => setMonth(Number(e.target.value))}
                            className="bg-transparent text-sm font-medium px-3 py-1.5 rounded-md text-slate-700 dark:text-slate-200 focus:outline-none cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700"
                        >
                            {Array.from({ length: 12 }, (_, i) => (
                                <option key={i + 1} value={i + 1}>{new Date(0, i).toLocaleString('default', { month: 'short' })}</option>
                            ))}
                        </select>
                        <div className="w-px bg-slate-200 dark:bg-slate-700 my-1 mx-1"></div>
                        <select
                            value={year}
                            onChange={(e) => setYear(Number(e.target.value))}
                            className="bg-transparent text-sm font-medium px-3 py-1.5 rounded-md text-slate-700 dark:text-slate-200 focus:outline-none cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700"
                        >
                            <option value={2024}>2024</option>
                            <option value={2025}>2025</option>
                            <option value={2026}>2026</option>
                        </select>
                    </div>

                    <button onClick={handleExportPDF} className="p-2.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 hover:text-primary transition-colors tooltip" title="Export PDF">
                        <Download size={20} />
                    </button>

                    <button className="flex items-center gap-2 bg-gradient-to-r from-primary to-cyan-500 hover:from-sky-600 hover:to-cyan-600 text-white px-5 py-2.5 rounded-xl shadow-lg shadow-sky-500/20 font-medium transition-all hover:scale-105 active:scale-95">
                        <Plus size={20} />
                        <span>Add Expense</span>
                    </button>
                </div>
            </div>

            {/* Insight Banner */}
            {data?.insight && (
                <div className={clsx(
                    "p-5 rounded-2xl border flex items-start gap-4 shadow-sm backdrop-blur-sm",
                    data?.alert
                        ? "bg-red-50/50 border-red-200 text-red-700 dark:bg-red-900/10 dark:border-red-900/30 dark:text-red-400"
                        : "bg-sky-50/50 border-sky-200 text-sky-700 dark:bg-sky-900/10 dark:border-sky-900/30 dark:text-sky-400"
                )}>
                    <div className={clsx("p-2 rounded-full", data?.alert ? "bg-red-100 dark:bg-red-900/30" : "bg-sky-100 dark:bg-sky-900/30")}>
                        {data?.alert ? <AlertTriangle size={20} /> : <TrendingUp size={20} />}
                    </div>
                    <div>
                        <h4 className="font-bold text-lg">Monthly Insight</h4>
                        <p className="opacity-90 leading-relaxed mt-1 text-sm sm:text-base">{data.insight}</p>
                    </div>
                </div>
            )}

            {/* Stats Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                <StatCard
                    title="Total Budget"
                    value={data?.budget}
                    icon={Wallet}
                    color="bg-sky-500 text-sky-500"
                />
                <StatCard
                    title="Total Spent"
                    value={data?.totalSpent}
                    icon={ArrowUpRight}
                    color="bg-orange-500 text-orange-500"
                    subtext={`${Math.round((data?.totalSpent / (data?.budget || 1)) * 100)}%`}
                />
                <StatCard
                    title="Remaining"
                    value={data?.remaining}
                    icon={PiggyBank}
                    color={data?.remaining < 0 ? "bg-red-500 text-red-500" : "bg-emerald-500 text-emerald-500"}
                />
                <StatCard
                    title="Wasted Money"
                    value={data?.totalWasted}
                    icon={ArrowDownRight}
                    color="bg-red-500 text-red-500"
                />
            </div>

            {/* Charts or Empty State */}
            {data?.totalSpent === 0 ? (
                <div className="card py-16 flex flex-col items-center justify-center text-center">
                    <div className="bg-slate-100 dark:bg-slate-800 p-6 rounded-full mb-6">
                        <FileText size={48} className="text-slate-400" />
                    </div>
                    <h3 className="text-xl font-bold text-slate-700 dark:text-slate-200 mb-2">No expenses yet</h3>
                    <p className="text-slate-500 max-w-sm mx-auto mb-8">
                        Start tracking your spending to see analytics and insights here.
                    </p>
                    <button className="btn btn-primary">
                        Add your first entry
                    </button>
                </div>
            ) : (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Daily Spending Bar Chart Placeholder */}
                    <div className="card lg:col-span-2 flex flex-col">
                        <h3 className="text-xl font-bold mb-6 text-slate-800 dark:text-white flex items-center gap-2">
                            Daily Spending <span className="text-xs font-normal text-slate-400 px-2 py-1 bg-slate-100 dark:bg-slate-800 rounded-full border border-slate-200 dark:border-slate-700">Last 30 Days</span>
                        </h3>
                        <div className="flex-1 flex items-end justify-between gap-1 h-64 mt-auto">
                            {data?.dailyData?.map((val, idx) => (
                                <div
                                    key={idx}
                                    style={{ height: `${Math.max(4, Math.min(100, (val / (Math.max(...data.dailyData) || 1)) * 100))}%` }}
                                    className="flex-1 bg-sky-200/50 dark:bg-sky-500/20 rounded-t-sm hover:bg-sky-500 dark:hover:bg-sky-500 transition-all relative group"
                                >
                                    <div className="opacity-0 group-hover:opacity-100 absolute bottom-full mb-2 left-1/2 -translate-x-1/2 bg-slate-900 text-white text-xs px-2 py-1 rounded shadow-lg pointer-events-none transition-opacity whitespace-nowrap z-20">
                                        Day {idx + 1}: ₹{val}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Donut Chart */}
                    <div className="card flex flex-col">
                        <h3 className="text-xl font-bold mb-6 text-slate-800 dark:text-white">Category Split</h3>
                        <div className="h-64 relative flex-1 min-h-[250px]">
                            {pieData.length > 0 ? (
                                <ResponsiveContainer width="100%" height="100%">
                                    <PieChart>
                                        <Pie
                                            data={pieData}
                                            cx="50%"
                                            cy="50%"
                                            innerRadius={70}
                                            outerRadius={90}
                                            paddingAngle={4}
                                            dataKey="value"
                                            stroke="none"
                                        >
                                            {pieData.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                            ))}
                                            <Label
                                                value={`₹${data.totalSpent?.toLocaleString()}`}
                                                position="center"
                                                className="fill-slate-800 dark:fill-white font-bold text-xl"
                                            />
                                        </Pie>
                                        <Tooltip
                                            formatter={(value) => `₹${value}`}
                                            contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', borderRadius: '8px', color: '#fff' }}
                                            itemStyle={{ color: '#fff' }}
                                        />
                                    </PieChart>
                                </ResponsiveContainer>
                            ) : (
                                <div className="flex items-center justify-center h-full text-slate-400">No data available</div>
                            )}
                        </div>
                        <div className="mt-6 space-y-3">
                            {pieData.slice(0, 4).map((entry, index) => (
                                <div key={index} className="flex justify-between items-center text-sm p-2 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-lg transition-colors">
                                    <div className="flex items-center gap-3">
                                        <div className="w-3 h-3 rounded-full shadow-sm" style={{ backgroundColor: COLORS[index % COLORS.length] }}></div>
                                        <span className="text-slate-600 dark:text-slate-300 font-medium">{entry.name}</span>
                                    </div>
                                    <span className="font-bold text-slate-800 dark:text-slate-200">₹{entry.value.toLocaleString()}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Dashboard;
